### ISSUE TITLE
dist/src/server/routes/api not found

### ISSUE THREAD

**Issue by ondrejrohon** [jonluca/vite-typescript-ssr-react#5]
How to reproduce:
1. Clone this repo
2. Yarn install
3. yarn serve

you get this error:
```
yarn run v1.22.17
$ yarn build && cross-env NODE_ENV=production node --experimental-modules dist/server.js
$ tsc -p tsconfig.prod.json && yarn build:client && yarn build:server && yarn copy-files
$ vite build --outDir dist/client
vite v2.8.1 building for production...
✓ 32 modules transformed.
dist/client/index.html                  0.65 KiB
dist/client/assets/index.1305d8da.js    3.58 KiB / gzip: 1.34 KiB
dist/client/assets/index.3ad06a7e.css   9.59 KiB / gzip: 3.19 KiB
dist/client/assets/vendor.7cb176a6.js   202.63 KiB / gzip: 50.71 KiB
$ vite build --ssr src/client/entry-server.tsx --outDir dist/server
vite v2.8.1 building SSR bundle for production...
✓ 6 modules transformed.
dist/server/entry-server.js   3.11 KiB
$ copyfiles static/* dist/assets && copyfiles index.html dist
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/ondrejrohon/Desktop/react-tailwind-express-typescript/vite-typescript-ssr-react/dist/src/server/routes/api' imported from /Users/ondrejrohon/Desktop/react-tailwind-express-typescript/vite-typescript-ssr-react/dist/server.js
    at finalizeResolution (internal/modules/esm/resolve.js:271:11)
    at moduleResolve (internal/modules/esm/resolve.js:694:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:72:40)
    at link (internal/modules/esm/module_job.js:71:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Thanks for looking into this and for making this starter. Looks amazing!

**Comment by ondrejrohon** [comment]
also, when you go around this problem by replacing https://github.com/jonluca/vite-typescript-ssr-react/blob/master/server.ts#L49 with
```
app.use("/api", (req, res) => {
    res.send('ok').status(200).end();
  });
```

I get this error:
```
ReferenceError: require is not defined
    at file:///Users/ondrejrohon/Desktop/vite-typescript-ssr-react/dist/server.js:57:37
    at Layer.handle [as handle_request] (/Users/ondrejrohon/Desktop/vite-typescript-ssr-react/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/ondrejrohon/Desktop/vite-typescript-ssr-react/node_modules/express/lib/router/index.js:323:13)
    at /Users/ondrejrohon/Desktop/vite-typescript-ssr-react/node_modules/express/lib/router/index.js:284:7
    at param (/Users/ondrejrohon/Desktop/vite-typescript-ssr-react/node_modules/express/lib/router/index.js:360:14)
    at param (/Users/ondrejrohon/Desktop/vite-typescript-ssr-react/node_modules/express/lib/router/index.js:371:14)
    at Function.process_params (/Users/ondrejrohon/Desktop/vite-typescript-ssr-react/node_modules/express/lib/router/index.js:416:3)
    at next (/Users/ondrejrohon/Desktop/vite-typescript-ssr-react/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/Users/ondrejrohon/Desktop/vite-typescript-ssr-react/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:526:28)
```

**Comment by ondrejrohon** [comment]
Node version v17.5.0, MacOS 12.1

**Comment by jonluca** [comment]
Adding `--experimental-specifier-resolution=node` to the serve command in `package.json` should fix it. I've updated it in this commit https://github.com/jonluca/vite-typescript-ssr-react/commit/b61ad38f3b737f0aa70e5a6a396d5a18053c682a

**Comment by jonluca** [comment]
I've also added a new command, `serve:local`, to use the native vite serving logic. Should be faster than SSR if that's not something you care about
